env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: 
  no-irregular-whitespace:
    - 2
    - skipRegExps: true

